# Generated by Django 4.1 on 2022-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_cbv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_id',
        ),
        migrations.AddField(
            model_name='room',
            name='user_id',
            field=models.ManyToManyField(to='raw_cbv.user', verbose_name='유저'),
        ),
    ]
